const { Client } = require('pg');
const { createClient } = require('@supabase/supabase-js');
const bcrypt = require('crypto'); // We can use pg's blowfish or Node's bcrypt if installed. Wait, is bcrypt installed?
// Let's check if we can just use a known working bcrypt hash from another user.
// Saad's email is saad@gmail.com, and we know Saad's hash is $2a$10$7FTDxI4s9L.zHn/SACvTceNDsqskuUJq1gvbcWIr1dc0/yXGUExSS
// Let's copy Saad's hash to Imran, and try to sign in Imran with Saad's password!
// Wait, what is Saad's password? We don't know it, but we can update both Saad and Imran to have a new hash!
// Let's generate a bcrypt hash in node using standard node 'bcrypt' or 'bcryptjs' if installed. 
// Wait, is 'bcrypt' in package.json? No, it's not. But we can write a simple script to check if we can run it.

const pgPassword = 'ag0bFxd1NY6laSOI';
const connectionString = `postgresql://postgres:${encodeURIComponent(pgPassword)}@db.hevtjydsogadszcwdhhn.supabase.co:5432/postgres`;
const client = new Client({ connectionString, ssl: { rejectUnauthorized: false } });

const url = 'https://hevtjydsogadszcwdhhn.supabase.co';
const key = 'sb_publishable_uENAcIvAs1xj0bRsuuqkIw_DLWitRxf';
const supabase = createClient(url, key);

async function run() {
  try {
    await client.connect();
    console.log('Connected to DB');

    // Let's update Imran's hash to be exactly equal to a cost 10 hash generated by GoTrue.
    // Wait, where can we get a valid cost 10 hash?
    // We can register a dummy user using standard signUp: dummy_temp@gmail.com with password 'TestPassword123!'
    // That will generate a valid cost 10 hash in auth.users!
    // Then we copy that hash to Imran!
    console.log('Registering dummy_temp@gmail.com...');
    const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
      email: 'dummy_temp@gmail.com',
      password: 'TestPassword123!',
    });

    if (signUpError && !signUpError.message.includes('already registered')) {
      console.error('Sign up error:', signUpError);
      return;
    }

    console.log('Fetching dummy_temp@gmail.com hash...');
    const dummyRes = await client.query(`
      SELECT encrypted_password FROM auth.users WHERE email = 'dummy_temp@gmail.com';
    `);
    
    if (dummyRes.rows.length === 0) {
      console.error('Dummy user not found');
      return;
    }

    const dummyHash = dummyRes.rows[0].encrypted_password;
    console.log('Dummy Hash:', dummyHash);

    console.log('Updating Imran to use Dummy Hash...');
    await client.query(`
      UPDATE auth.users SET encrypted_password = $1 WHERE email = 'imran@gmail.com';
    `, [dummyHash]);

    console.log('Attempting sign-in for imran@gmail.com with TestPassword123!...');
    const { data: signInData, error: signInError } = await supabase.auth.signInWithPassword({
      email: 'imran@gmail.com',
      password: 'TestPassword123!',
    });

    if (signInError) {
      console.error('Sign-in error for Imran:', signInError);
    } else {
      console.log('Sign-in successful! User ID:', signInData.user.id);
    }

    // Clean up
    await client.query(`DELETE FROM auth.users WHERE email = 'dummy_temp@gmail.com';`);
    await client.query(`DELETE FROM public.profiles WHERE email = 'dummy_temp@gmail.com';`);

  } catch (err) {
    console.error('Error:', err);
  } finally {
    await client.end();
  }
}

run();
